### ISSUE TITLE
Bot: Miner's harvesting slot location should include room name

### ISSUE THREAD

**Issue by nrnoble** [Jomik/screeps-ai#1]
A bit of a corner case. Currently, the miner's slot location is defined as [x,y]. When traveling to the slot location, if the miner leaves the room, the miner will not return. 

This issue occurred a couple of times because in one of my rooms when the miner was traveling to the slot location, it was next to one of the room's exits, and it left the room when avoiding other creeps on the same path, thus the miner targeted the wrong x,y location in another room.

consider changing to:
miner.memory.slot ={x,y,roomName}

**Comment by Jomik** [comment]
Oh, that's pretty fun.
This is simply really, really early game code that I put up.
I think I would plan to have the miners managed by a process that is assigned a room, so the room name would then be known there.
