### ISSUE TITLE
update @yarn-tool/resolve-package in yarn.lock from 1.0.46 --> 1.0.47 (or greater)

### ISSUE THREAD

**Issue by nrnoble** [Jomik/screeps-ai#10]
Consider updating to yarn-tool/resolve-package in yarn.lock from 1.0.46 --> 1.0.47 (or greater)

I am getting the following error when running "yarn" to update dependencies:

➤ YN0000: ┌ Resolution step
➤ YN0002: │ @yarn-tool/resolve-package@npm:1.0.46 doesn't provide @types/node (pa74b7), requested by upath2
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 624ms

upgrading "@yarn-tool/resolve-package" to 1.0.47 eliminates this error.

I fixed this problem by removing this block from "yarn.lock" and then ran "yarn" to install 1.0.47

"@yarn-tool/resolve-package@npm:^1.0.40":
  version: 1.0.46
  resolution: "@yarn-tool/resolve-package@npm:1.0.46"
  dependencies:
    pkg-dir: "npm:< 6 >= 5"
    tslib: "npm:^2.3.1"
    upath2: "npm:^3.1.12"
  checksum: 49ece5c526d2bac1f896f360b6a736bf4da6f2489aaa3ea8a5dee5446eecdd9d6697c96a080060ece6d8a4b11b9f7816546ae8d2f42df45400f2fe1e2399383a
  languageName: 
  node
  linkType: hard

**Comment by Jomik** [comment]
Fixed on GitLab.
